spring:
  profiles.active: default

---
spring:
  profiles: default

region:
  hostSuffix: .com
  currencyCode: USD
  patternShortDate: MM-dd-YYYY

  locales:
    en_CA:
      hostSuffix: .ca
      currencyCode: CAD
      patternShortDate: dd-MM-YYYY
    en_GB:
      hostSuffix: .co.uk
      currencyCode: GBD
      patternShortDate: dd-MM-YYYY

---
spring:
  profiles: production

